#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Fix untuk OpenSSL di Windows (XAMPP) agar library WebPush (Minishlink) bisa buat key
if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN' && empty(getenv('OPENSSL_CONF'))) {
    $xamppOpenSslConf = 'C:\xampp\apache\conf\openssl.cnf';
    if (file_exists($xamppOpenSslConf)) {
        putenv("OPENSSL_CONF={$xamppOpenSslConf}");
    }
}

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
